services:

  # FYI https://www.jenkins.io/doc/book/installing/docker/
  jenkins:
    image: jenkins/jenkins # :latest (weekly), :lts, :jdk17, :jdk11, :lts-jdk17, etc
    ports:
      - "127.0.0.1:8081:8080" # drop 127.0.0.1: if you want remote access to Jenkins
    networks:
      - my-network
    volumes:
      - jenkins_home:/var/jenkins_home # persist data across container recreation, updating image, etc
    restart: unless-stopped # when you instruct Jenkins to restart this ensures it will start back up, also if your machine reboots when Docker starts back up it will start Jenkins back up too

  # https://hub.docker.com/r/bitnami/openldap/
  openldap:
    image: bitnami/openldap:2
    ports:
      - '1389:1389'
      - '1636:1636'
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
    networks:
      - my-network
    volumes:
      - 'openldap_data:/bitnami/openldap'
    restart: unless-stopped
  email:
    image: mailhog/mailhog
    platform: linux/amd64 # for Apple Silicon macs
    ports:
      # - "127.0.0.1:1025:1025" # SMTP (when Jenkins and MailHog both run via Docker Compose they share a network, so there is no need to publish a port to your host)
      - "127.0.0.1:8025:8025" # web UI
    restart: unless-stopped
    networks:
      - my-network

volumes:
  openldap_data:
    driver: local
  jenkins_home:

networks:
  my-network:
    driver: bridge

